config:
  webserver:
    expose_config: 'True'

dags:
  gitSync:
    enabled: true
    repo: https://github.com/cnboonhan/mlops
    branch: main
    rev: HEAD
    subPath: "etl_pipeline/dags"
    wait: 5
    depth: 1
    containerName: "git-sync"
